### ISSUE TITLE
Running container image as a Github Action

### ISSUE THREAD

**Issue by lewismc** [jamescooke/openapi-validator-docker#129]
Hi @jamescooke thank you for putting this image together... 👍 
I've been running it as part of a Github Actions workflow as follows and everything is going fine...
```
jobs:
  lint_openapi:
    name: Lint OpenAPI Specification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume
      - name: Lint OpenAPI Specification
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: jamescooke/openapi-validator:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            lint-openapi openapi.yaml
            exit $?
```
Recently however I needed to essentially [customize/ignore one of the IBM default rules](https://github.com/IBM/openapi-validator/blob/main/docs/ibm-cloud-rules.md#customization) as follows
```
extends: '@ibm-cloud/openapi-ruleset'
rules:
  #toggled off as this is IBM-specific
  request-body-object: off
```
Running `lint-openapi` locally without Docker, I can then pass the custom ruleset as follows `lint-openapi --ruleset custom-rules.yaml openapi.yaml`. When I try to integrate this into the above Github Actions workflow, it looks like the `--ruleset` parameter is not being interpreted by the container image.

```
jobs:
  lint_openapi:
    name: Lint OpenAPI Specification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume
      - name: Lint OpenAPI Specification
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: jamescooke/openapi-validator:latest
          options: -v ${{ github.workspace }}:/data 
          run: |
            lint-openapi --ruleset custom-rules.yaml openapi.yaml 
            exit $?
```

Returns non-zero exit code and fails by CI build.
Any ideas what I am doing wrong?
Thank you
